name: ${name}
version: ${version}
main: com.gmail.ljuangbminecraft.suspiciousmooshroom.SuspiciousMooshroom
description: ${description}
api-version: 1.13
commands:
  mooshroomitem:
    description: Get a custom item from ${name}.
    usage: "Usage: /mooshroomitem [itemid]"
    aliases: [mooitem]
  mooshroomconfig:
    description: Reloads ${name}'s config without having to restart the server.
    usage: "Usage: /mooshroomconfig"
    aliases: [mooconfig, mooreload]